{
    'name': 'Fleet Partner Dashboard',
    'version': '15.0.1.0.3',
    'summary': 'Manage fleet drivers, orders, issues, and product types',
    'category': 'Fleet',
    'author': 'Chi Fei Nim',
    'website': 'https://github.com/chifeinim',
    'depends': ['base', 'mail', 'web',],
    'data': [
        'data/sequence.xml',
        'data/ir_sequence.xml',
        'data/ir_cron_supabase.xml',
        'security/ir.model.access.csv',
        'views/fleet_call_note_views.xml',
        'views/fleet_performance_issue_rule_views.xml',
        'views/fleet_driver_views.xml',
        'views/fleet_car_views.xml',
        'views/fleet_order_views.xml',
        'views/product_type_views.xml',
        'views/driver_dashboard.xml',
        'views/driver_supply_hours_views.xml',
        'views/issue_views.xml',
        'views/issue_views_media.xml',
        'views/issue_call_note_views.xml',
        'views/queue_views.xml',
        'views/menu_views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'fleet_partner_dashboard/static/src/lib/chart.umd.min.js',
            'fleet_partner_dashboard/static/src/js/dashboard/driver_dashboard.js',
            'fleet_partner_dashboard/static/src/js/dashboard/performance_dashboard.js',
            'fleet_partner_dashboard/static/src/js/dashboard/low_performers_dashboard.js',
            'fleet_partner_dashboard/static/src/js/dashboard/call_center_dashboard.js',
            'fleet_partner_dashboard/static/src/css/dashboard.css',
        ],
        'web.assets_qweb': [
            'fleet_partner_dashboard/static/src/xml/driver_dashboard_templates.xml',
            'fleet_partner_dashboard/static/src/xml/performance_dashboard_templates.xml',
            'fleet_partner_dashboard/static/src/xml/low_performers_dashboard_templates.xml',
            'fleet_partner_dashboard/static/src/xml/call_center_dashboard_templates.xml',
        ],
    },
    'installable': True,
    'application': True,
} # pyright: ignore[reportUnusedExpression]
